=head1 NAME

GStreamer::Query::Convert

=cut


=head1 METHODS

=head2 GstQuery = GStreamer::Query::Convert-E<gt>B<new> ($src_format, $value, $dest_format)

=over

=item * $src_format (GStreamer::Format) 

=item * $value (64 bit integer) 

=item * $dest_format (GStreamer::Format) 

=back

=head2 list = $query-E<gt>B<convert> ($src_format=0, $src_value=0, $dest_format=0, $dest_value=0)

=over

=item * $src_format (GStreamer::Format) 

=item * $src_value (64 bit integer) 

=item * $dest_format (GStreamer::Format) 

=item * $dest_value (64 bit integer) 

=back



=cut


=head1 ENUMS AND FLAGS

=head2 enum GStreamer::Format

=over

=item * 'undefined' / 'GST_FORMAT_UNDEFINED'

=item * 'default' / 'GST_FORMAT_DEFAULT'

=item * 'bytes' / 'GST_FORMAT_BYTES'

=item * 'time' / 'GST_FORMAT_TIME'

=item * 'buffers' / 'GST_FORMAT_BUFFERS'

=item * 'percent' / 'GST_FORMAT_PERCENT'

=back




=cut


=head1 SEE ALSO

L<GStreamer>


=cut


=head1 COPYRIGHT

Copyright (C) 2005-2014 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<GStreamer> for a full notice.



=cut

