/* This file is automatically generated. Any changes made here will be lost. */

/* This header defines simple perlapi-ish macros for creating SV wrappers
 * and extracting the GPerl value from SV wrappers.  These macros are used
 * by the autogenerated typemaps, and are defined here so that you can use
 * the same logic anywhere in your code (e.g., if you handle the argument
 * stack by hand instead of using the typemap). */

#ifdef WEBKIT_TYPE_WEB_VIEW
  /* GObject derivative WebKitWebView */
# define SvWebKitWebView(sv)	((WebKitWebView*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_VIEW))
# define newSVWebKitWebView(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebView WebKitWebView_ornull;
# define SvWebKitWebView_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebView(sv) : NULL)
# define newSVWebKitWebView_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebView WebKitWebView_noinc;
#define newSVWebKitWebView_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebView WebKitWebView_noinc_ornull;
#define newSVWebKitWebView_noinc_ornull(val)	((val) ? newSVWebKitWebView_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_VIEW */

#ifdef WEBKIT_TYPE_WEB_SETTINGS
  /* GObject derivative WebKitWebSettings */
# define SvWebKitWebSettings(sv)	((WebKitWebSettings*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_SETTINGS))
# define newSVWebKitWebSettings(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebSettings WebKitWebSettings_ornull;
# define SvWebKitWebSettings_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebSettings(sv) : NULL)
# define newSVWebKitWebSettings_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebSettings WebKitWebSettings_noinc;
#define newSVWebKitWebSettings_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebSettings WebKitWebSettings_noinc_ornull;
#define newSVWebKitWebSettings_noinc_ornull(val)	((val) ? newSVWebKitWebSettings_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_SETTINGS */

#ifdef WEBKIT_TYPE_WEB_HISTORY_ITEM
  /* GObject derivative WebKitWebHistoryItem */
# define SvWebKitWebHistoryItem(sv)	((WebKitWebHistoryItem*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_HISTORY_ITEM))
# define newSVWebKitWebHistoryItem(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebHistoryItem WebKitWebHistoryItem_ornull;
# define SvWebKitWebHistoryItem_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebHistoryItem(sv) : NULL)
# define newSVWebKitWebHistoryItem_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebHistoryItem WebKitWebHistoryItem_noinc;
#define newSVWebKitWebHistoryItem_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebHistoryItem WebKitWebHistoryItem_noinc_ornull;
#define newSVWebKitWebHistoryItem_noinc_ornull(val)	((val) ? newSVWebKitWebHistoryItem_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_HISTORY_ITEM */

#ifdef WEBKIT_TYPE_WEB_FRAME
  /* GObject derivative WebKitWebFrame */
# define SvWebKitWebFrame(sv)	((WebKitWebFrame*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_FRAME))
# define newSVWebKitWebFrame(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebFrame WebKitWebFrame_ornull;
# define SvWebKitWebFrame_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebFrame(sv) : NULL)
# define newSVWebKitWebFrame_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebFrame WebKitWebFrame_noinc;
#define newSVWebKitWebFrame_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebFrame WebKitWebFrame_noinc_ornull;
#define newSVWebKitWebFrame_noinc_ornull(val)	((val) ? newSVWebKitWebFrame_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_FRAME */

#ifdef WEBKIT_TYPE_WEB_BACK_FORWARD_LIST
  /* GObject derivative WebKitWebBackForwardList */
# define SvWebKitWebBackForwardList(sv)	((WebKitWebBackForwardList*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_BACK_FORWARD_LIST))
# define newSVWebKitWebBackForwardList(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebBackForwardList WebKitWebBackForwardList_ornull;
# define SvWebKitWebBackForwardList_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebBackForwardList(sv) : NULL)
# define newSVWebKitWebBackForwardList_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebBackForwardList WebKitWebBackForwardList_noinc;
#define newSVWebKitWebBackForwardList_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebBackForwardList WebKitWebBackForwardList_noinc_ornull;
#define newSVWebKitWebBackForwardList_noinc_ornull(val)	((val) ? newSVWebKitWebBackForwardList_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_BACK_FORWARD_LIST */

#ifdef WEBKIT_TYPE_NETWORK_REQUEST
  /* GObject derivative WebKitNetworkRequest */
# define SvWebKitNetworkRequest(sv)	((WebKitNetworkRequest*)gperl_get_object_check (sv, WEBKIT_TYPE_NETWORK_REQUEST))
# define newSVWebKitNetworkRequest(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitNetworkRequest WebKitNetworkRequest_ornull;
# define SvWebKitNetworkRequest_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitNetworkRequest(sv) : NULL)
# define newSVWebKitNetworkRequest_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitNetworkRequest WebKitNetworkRequest_noinc;
#define newSVWebKitNetworkRequest_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitNetworkRequest WebKitNetworkRequest_noinc_ornull;
#define newSVWebKitNetworkRequest_noinc_ornull(val)	((val) ? newSVWebKitNetworkRequest_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_NETWORK_REQUEST */

#ifdef WEBKIT_TYPE_WEB_INSPECTOR
  /* GObject derivative WebKitWebInspector */
# define SvWebKitWebInspector(sv)	((WebKitWebInspector*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_INSPECTOR))
# define newSVWebKitWebInspector(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebInspector WebKitWebInspector_ornull;
# define SvWebKitWebInspector_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebInspector(sv) : NULL)
# define newSVWebKitWebInspector_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebInspector WebKitWebInspector_noinc;
#define newSVWebKitWebInspector_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebInspector WebKitWebInspector_noinc_ornull;
#define newSVWebKitWebInspector_noinc_ornull(val)	((val) ? newSVWebKitWebInspector_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_INSPECTOR */

#ifdef WEBKIT_TYPE_WEB_WINDOW_FEATURES
  /* GObject derivative WebKitWebWindowFeatures */
# define SvWebKitWebWindowFeatures(sv)	((WebKitWebWindowFeatures*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_WINDOW_FEATURES))
# define newSVWebKitWebWindowFeatures(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebWindowFeatures WebKitWebWindowFeatures_ornull;
# define SvWebKitWebWindowFeatures_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebWindowFeatures(sv) : NULL)
# define newSVWebKitWebWindowFeatures_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebWindowFeatures WebKitWebWindowFeatures_noinc;
#define newSVWebKitWebWindowFeatures_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebWindowFeatures WebKitWebWindowFeatures_noinc_ornull;
#define newSVWebKitWebWindowFeatures_noinc_ornull(val)	((val) ? newSVWebKitWebWindowFeatures_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_WINDOW_FEATURES */

#ifdef WEBKIT_TYPE_DOWNLOAD
  /* GObject derivative WebKitDownload */
# define SvWebKitDownload(sv)	((WebKitDownload*)gperl_get_object_check (sv, WEBKIT_TYPE_DOWNLOAD))
# define newSVWebKitDownload(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitDownload WebKitDownload_ornull;
# define SvWebKitDownload_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitDownload(sv) : NULL)
# define newSVWebKitDownload_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitDownload WebKitDownload_noinc;
#define newSVWebKitDownload_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitDownload WebKitDownload_noinc_ornull;
#define newSVWebKitDownload_noinc_ornull(val)	((val) ? newSVWebKitDownload_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_DOWNLOAD */

#ifdef WEBKIT_TYPE_DOWNLOAD_STATUS
  /* GEnum WebKitDownloadStatus */
# define SvWebKitDownloadStatus(sv)	((WebKitDownloadStatus)gperl_convert_enum (WEBKIT_TYPE_DOWNLOAD_STATUS, sv))
# define newSVWebKitDownloadStatus(val)	(gperl_convert_back_enum (WEBKIT_TYPE_DOWNLOAD_STATUS, val))
#endif /* WEBKIT_TYPE_DOWNLOAD_STATUS */

#ifdef WEBKIT_TYPE_WEB_NAVIGATION_ACTION
  /* GObject derivative WebKitWebNavigationAction */
# define SvWebKitWebNavigationAction(sv)	((WebKitWebNavigationAction*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_NAVIGATION_ACTION))
# define newSVWebKitWebNavigationAction(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebNavigationAction WebKitWebNavigationAction_ornull;
# define SvWebKitWebNavigationAction_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebNavigationAction(sv) : NULL)
# define newSVWebKitWebNavigationAction_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebNavigationAction WebKitWebNavigationAction_noinc;
#define newSVWebKitWebNavigationAction_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebNavigationAction WebKitWebNavigationAction_noinc_ornull;
#define newSVWebKitWebNavigationAction_noinc_ornull(val)	((val) ? newSVWebKitWebNavigationAction_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_NAVIGATION_ACTION */

#ifdef WEBKIT_TYPE_WEB_NAVIGATION_REASON
  /* GEnum WebKitWebNavigationReason */
# define SvWebKitWebNavigationReason(sv)	((WebKitWebNavigationReason)gperl_convert_enum (WEBKIT_TYPE_WEB_NAVIGATION_REASON, sv))
# define newSVWebKitWebNavigationReason(val)	(gperl_convert_back_enum (WEBKIT_TYPE_WEB_NAVIGATION_REASON, val))
#endif /* WEBKIT_TYPE_WEB_NAVIGATION_REASON */

#ifdef WEBKIT_TYPE_WEB_POLICY_DECISION
  /* GObject derivative WebKitWebPolicyDecision */
# define SvWebKitWebPolicyDecision(sv)	((WebKitWebPolicyDecision*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_POLICY_DECISION))
# define newSVWebKitWebPolicyDecision(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebPolicyDecision WebKitWebPolicyDecision_ornull;
# define SvWebKitWebPolicyDecision_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebPolicyDecision(sv) : NULL)
# define newSVWebKitWebPolicyDecision_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebPolicyDecision WebKitWebPolicyDecision_noinc;
#define newSVWebKitWebPolicyDecision_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebPolicyDecision WebKitWebPolicyDecision_noinc_ornull;
#define newSVWebKitWebPolicyDecision_noinc_ornull(val)	((val) ? newSVWebKitWebPolicyDecision_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_POLICY_DECISION */

#ifdef WEBKIT_TYPE_LOAD_STATUS
  /* GEnum WebKitLoadStatus */
# define SvWebKitLoadStatus(sv)	((WebKitLoadStatus)gperl_convert_enum (WEBKIT_TYPE_LOAD_STATUS, sv))
# define newSVWebKitLoadStatus(val)	(gperl_convert_back_enum (WEBKIT_TYPE_LOAD_STATUS, val))
#endif /* WEBKIT_TYPE_LOAD_STATUS */

#ifdef WEBKIT_TYPE_WEB_DATABASE
  /* GObject derivative WebKitWebDatabase */
# define SvWebKitWebDatabase(sv)	((WebKitWebDatabase*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_DATABASE))
# define newSVWebKitWebDatabase(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebDatabase WebKitWebDatabase_ornull;
# define SvWebKitWebDatabase_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebDatabase(sv) : NULL)
# define newSVWebKitWebDatabase_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebDatabase WebKitWebDatabase_noinc;
#define newSVWebKitWebDatabase_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebDatabase WebKitWebDatabase_noinc_ornull;
#define newSVWebKitWebDatabase_noinc_ornull(val)	((val) ? newSVWebKitWebDatabase_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_DATABASE */

#ifdef WEBKIT_TYPE_WEB_DATA_SOURCE
  /* GObject derivative WebKitWebDataSource */
# define SvWebKitWebDataSource(sv)	((WebKitWebDataSource*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_DATA_SOURCE))
# define newSVWebKitWebDataSource(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebDataSource WebKitWebDataSource_ornull;
# define SvWebKitWebDataSource_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebDataSource(sv) : NULL)
# define newSVWebKitWebDataSource_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebDataSource WebKitWebDataSource_noinc;
#define newSVWebKitWebDataSource_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebDataSource WebKitWebDataSource_noinc_ornull;
#define newSVWebKitWebDataSource_noinc_ornull(val)	((val) ? newSVWebKitWebDataSource_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_DATA_SOURCE */

#ifdef WEBKIT_TYPE_WEB_RESOURCE
  /* GObject derivative WebKitWebResource */
# define SvWebKitWebResource(sv)	((WebKitWebResource*)gperl_get_object_check (sv, WEBKIT_TYPE_WEB_RESOURCE))
# define newSVWebKitWebResource(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitWebResource WebKitWebResource_ornull;
# define SvWebKitWebResource_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitWebResource(sv) : NULL)
# define newSVWebKitWebResource_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitWebResource WebKitWebResource_noinc;
#define newSVWebKitWebResource_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitWebResource WebKitWebResource_noinc_ornull;
#define newSVWebKitWebResource_noinc_ornull(val)	((val) ? newSVWebKitWebResource_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_WEB_RESOURCE */

#ifdef WEBKIT_TYPE_SECURITY_ORIGIN
  /* GObject derivative WebKitSecurityOrigin */
# define SvWebKitSecurityOrigin(sv)	((WebKitSecurityOrigin*)gperl_get_object_check (sv, WEBKIT_TYPE_SECURITY_ORIGIN))
# define newSVWebKitSecurityOrigin(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitSecurityOrigin WebKitSecurityOrigin_ornull;
# define SvWebKitSecurityOrigin_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitSecurityOrigin(sv) : NULL)
# define newSVWebKitSecurityOrigin_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitSecurityOrigin WebKitSecurityOrigin_noinc;
#define newSVWebKitSecurityOrigin_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitSecurityOrigin WebKitSecurityOrigin_noinc_ornull;
#define newSVWebKitSecurityOrigin_noinc_ornull(val)	((val) ? newSVWebKitSecurityOrigin_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_SECURITY_ORIGIN */

#ifdef WEBKIT_TYPE_NETWORK_RESPONSE
  /* GObject derivative WebKitNetworkResponse */
# define SvWebKitNetworkResponse(sv)	((WebKitNetworkResponse*)gperl_get_object_check (sv, WEBKIT_TYPE_NETWORK_RESPONSE))
# define newSVWebKitNetworkResponse(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitNetworkResponse WebKitNetworkResponse_ornull;
# define SvWebKitNetworkResponse_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitNetworkResponse(sv) : NULL)
# define newSVWebKitNetworkResponse_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitNetworkResponse WebKitNetworkResponse_noinc;
#define newSVWebKitNetworkResponse_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitNetworkResponse WebKitNetworkResponse_noinc_ornull;
#define newSVWebKitNetworkResponse_noinc_ornull(val)	((val) ? newSVWebKitNetworkResponse_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_NETWORK_RESPONSE */

#ifdef WEBKIT_TYPE_GEOLOCATION_POLICY_DECISION
  /* GObject derivative WebKitGeolocationPolicyDecision */
# define SvWebKitGeolocationPolicyDecision(sv)	((WebKitGeolocationPolicyDecision*)gperl_get_object_check (sv, WEBKIT_TYPE_GEOLOCATION_POLICY_DECISION))
# define newSVWebKitGeolocationPolicyDecision(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitGeolocationPolicyDecision WebKitGeolocationPolicyDecision_ornull;
# define SvWebKitGeolocationPolicyDecision_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitGeolocationPolicyDecision(sv) : NULL)
# define newSVWebKitGeolocationPolicyDecision_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitGeolocationPolicyDecision WebKitGeolocationPolicyDecision_noinc;
#define newSVWebKitGeolocationPolicyDecision_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitGeolocationPolicyDecision WebKitGeolocationPolicyDecision_noinc_ornull;
#define newSVWebKitGeolocationPolicyDecision_noinc_ornull(val)	((val) ? newSVWebKitGeolocationPolicyDecision_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_GEOLOCATION_POLICY_DECISION */

#ifdef WEBKIT_TYPE_HIT_TEST_RESULT
  /* GObject derivative WebKitHitTestResult */
# define SvWebKitHitTestResult(sv)	((WebKitHitTestResult*)gperl_get_object_check (sv, WEBKIT_TYPE_HIT_TEST_RESULT))
# define newSVWebKitHitTestResult(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef WebKitHitTestResult WebKitHitTestResult_ornull;
# define SvWebKitHitTestResult_ornull(sv)	(gperl_sv_is_defined (sv) ? SvWebKitHitTestResult(sv) : NULL)
# define newSVWebKitHitTestResult_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
typedef WebKitHitTestResult WebKitHitTestResult_noinc;
#define newSVWebKitHitTestResult_noinc(val)	(gperl_new_object (G_OBJECT (val), TRUE))
typedef WebKitHitTestResult WebKitHitTestResult_noinc_ornull;
#define newSVWebKitHitTestResult_noinc_ornull(val)	((val) ? newSVWebKitHitTestResult_noinc(val) : &PL_sv_undef)
#endif /* WEBKIT_TYPE_HIT_TEST_RESULT */

#ifdef WEBKIT_TYPE_HIT_TEST_RESULT_CONTEXT
  /* GFlags WebKitHitTestResultContext */
# define SvWebKitHitTestResultContext(sv)	((WebKitHitTestResultContext)gperl_convert_flags (WEBKIT_TYPE_HIT_TEST_RESULT_CONTEXT, sv))
# define newSVWebKitHitTestResultContext(val)	(gperl_convert_back_flags (WEBKIT_TYPE_HIT_TEST_RESULT_CONTEXT, val))
#endif /* WEBKIT_TYPE_HIT_TEST_RESULT_CONTEXT */

#ifdef WEBKIT_TYPE_CACHE_MODEL
  /* GEnum WebKitCacheModel */
# define SvWebKitCacheModel(sv)	((WebKitCacheModel)gperl_convert_enum (WEBKIT_TYPE_CACHE_MODEL, sv))
# define newSVWebKitCacheModel(val)	(gperl_convert_back_enum (WEBKIT_TYPE_CACHE_MODEL, val))
#endif /* WEBKIT_TYPE_CACHE_MODEL */
