/* This file is automatically generated. Any changes made here will be lost. */

/* This header defines simple perlapi-ish macros for creating SV wrappers
 * and extracting the GPerl value from SV wrappers.  These macros are used
 * by the autogenerated typemaps, and are defined here so that you can use
 * the same logic anywhere in your code (e.g., if you handle the argument
 * stack by hand instead of using the typemap). */

#ifdef RSVG_TYPE_ERROR
  /* GEnum RsvgError */
# define SvRsvgError(sv)	((RsvgError)gperl_convert_enum (RSVG_TYPE_ERROR, sv))
# define newSVRsvgError(val)	(gperl_convert_back_enum (RSVG_TYPE_ERROR, val))
#endif /* RSVG_TYPE_ERROR */
