#define LIBRSVG_MAJOR_VERSION (2)
#define LIBRSVG_MINOR_VERSION (40)
#define LIBRSVG_MICRO_VERSION (9)
#define LIBRSVG_CHECK_VERSION(major,minor,micro) \
	(LIBRSVG_MAJOR_VERSION > (major) || \
	 (LIBRSVG_MAJOR_VERSION == (major) && LIBRSVG_MINOR_VERSION > (minor)) || \
	 (LIBRSVG_MAJOR_VERSION == (major) && LIBRSVG_MINOR_VERSION == (minor) && LIBRSVG_MICRO_VERSION >= (micro)))
