=head1 NAME

Gtk2::Scrollbar

=cut

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::Widget
                 +----Gtk2::Range
                      +----Gtk2::Scrollbar



=cut

=head1 INTERFACES

  Glib::Object::_Unregistered::AtkImplementorIface
  Gtk2::Buildable
  Gtk2::Orientable



=cut

=for object Gtk2::Scrollbar
=cut




=head1 STYLE PROPERTIES

=over

=item 'fixed-slider-length' (boolean : default false : readable / private)

Don't change slider size, just lock it to the minimum length

=item 'has-backward-stepper' (boolean : default true : readable / private)

Display the standard backward arrow button

=item 'has-forward-stepper' (boolean : default true : readable / private)

Display the standard forward arrow button

=item 'has-secondary-backward-stepper' (boolean : default false : readable / private)

Display a second backward arrow button on the opposite end of the scrollbar

=item 'has-secondary-forward-stepper' (boolean : default false : readable / private)

Display a second forward arrow button on the opposite end of the scrollbar

=item 'min-slider-length' (integer : default 21 : readable / private)

Minimum length of scrollbar slider

=back



=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::Widget>, L<Gtk2::Range>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

