=head1 NAME

Gtk2::ToolShell

=cut

=head1 HIERARCHY

  Glib::Interface
  +----Gtk2::ToolShell



=cut


=head1 METHODS

=head2 ellipsizemode = $shell-E<gt>B<get_ellipsize_mode> 

Since: gtk+ 2.20

=head2 iconsize = $shell-E<gt>B<get_icon_size> 

=head2 orientation = $shell-E<gt>B<get_orientation> 

=head2 $shell-E<gt>B<rebuild_menu> 

=head2 reliefstyle = $shell-E<gt>B<get_relief_style> 

=head2 toolbarstyle = $shell-E<gt>B<get_style> 

=head2 double = $shell-E<gt>B<get_text_alignment> 

Since: gtk+ 2.20

=head2 orientation = $shell-E<gt>B<get_text_orientation> 

Since: gtk+ 2.20

=head2 sizegroup or undef = $shell-E<gt>B<get_text_size_group> 

Since: gtk+ 2.20



=cut


=head1 ENUMS AND FLAGS

=head2 enum Gtk2::IconSize

=over

=item * 'invalid' / 'GTK_ICON_SIZE_INVALID'

=item * 'menu' / 'GTK_ICON_SIZE_MENU'

=item * 'small-toolbar' / 'GTK_ICON_SIZE_SMALL_TOOLBAR'

=item * 'large-toolbar' / 'GTK_ICON_SIZE_LARGE_TOOLBAR'

=item * 'button' / 'GTK_ICON_SIZE_BUTTON'

=item * 'dnd' / 'GTK_ICON_SIZE_DND'

=item * 'dialog' / 'GTK_ICON_SIZE_DIALOG'

=back


=head2 enum Gtk2::Orientation

=over

=item * 'horizontal' / 'GTK_ORIENTATION_HORIZONTAL'

=item * 'vertical' / 'GTK_ORIENTATION_VERTICAL'

=back


=head2 enum Gtk2::ReliefStyle

=over

=item * 'normal' / 'GTK_RELIEF_NORMAL'

=item * 'half' / 'GTK_RELIEF_HALF'

=item * 'none' / 'GTK_RELIEF_NONE'

=back


=head2 enum Gtk2::ToolbarStyle

=over

=item * 'icons' / 'GTK_TOOLBAR_ICONS'

=item * 'text' / 'GTK_TOOLBAR_TEXT'

=item * 'both' / 'GTK_TOOLBAR_BOTH'

=item * 'both-horiz' / 'GTK_TOOLBAR_BOTH_HORIZ'

=back


=head2 enum Pango::EllipsizeMode

=over

=item * 'none' / 'PANGO_ELLIPSIZE_NONE'

=item * 'start' / 'PANGO_ELLIPSIZE_START'

=item * 'middle' / 'PANGO_ELLIPSIZE_MIDDLE'

=item * 'end' / 'PANGO_ELLIPSIZE_END'

=back




=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Interface>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

