=head1 NAME

Gtk2::WebKit

=cut


=head1 METHODS

=head2 boolean = Gtk2::WebKit-E<gt>B<check_version> ($major, $minor, $micro)

=over

=item * $major (integer) 

=item * $minor (integer) 

=item * $micro (integer) 

=back

=head2 integer = Gtk2::WebKit-E<gt>B<major_version> 

=head2 integer = Gtk2::WebKit-E<gt>B<micro_version> 

=head2 integer = Gtk2::WebKit-E<gt>B<minor_version> 



=cut


=head1 SEE ALSO

L<Gtk2::WebKit>


=cut


=head1 COPYRIGHT

Copyright (C) 2008, Florian Ragwitz


=cut

