=head1 NAME

GStreamer::QueryType

=cut

=head1 HIERARCHY

  Glib::Enum
  +----GStreamer::QueryType



=cut


=head1 METHODS

=head2 querytype = GStreamer::QueryType::get_by_nick ($nick)

=over

=item * $nick (string) 

=back



=head2 list = GStreamer::QueryType::get_details ($type)

=over

=item * $type (GStreamer::QueryType) 

=back



=head2 querytype = GStreamer::QueryType::register ($nick, $description)

=over

=item * $nick (string) 

=item * $description (string) 

=back





=cut


=head1 ENUMS AND FLAGS

=head2 enum GStreamer::QueryType

=over

=item * 'none' / 'GST_QUERY_NONE'

=item * 'position' / 'GST_QUERY_POSITION'

=item * 'duration' / 'GST_QUERY_DURATION'

=item * 'latency' / 'GST_QUERY_LATENCY'

=item * 'jitter' / 'GST_QUERY_JITTER'

=item * 'rate' / 'GST_QUERY_RATE'

=item * 'seeking' / 'GST_QUERY_SEEKING'

=item * 'segment' / 'GST_QUERY_SEGMENT'

=item * 'convert' / 'GST_QUERY_CONVERT'

=item * 'formats' / 'GST_QUERY_FORMATS'

=item * 'buffering' / 'GST_QUERY_BUFFERING'

=item * 'custom' / 'GST_QUERY_CUSTOM'

=item * 'uri' / 'GST_QUERY_URI'

=back




=cut


=head1 SEE ALSO

L<GStreamer>, L<Glib::Enum>


=cut


=head1 COPYRIGHT

Copyright (C) 2005-2014 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<GStreamer> for a full notice.



=cut

