=head1 NAME

Gtk2::WebKit::NetworkResponse

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::WebKit::NetworkResponse



=cut


=head1 METHODS

=head2 string = $response-E<gt>B<_get_uri> 

=head2 networkresponse = Gtk2::WebKit::NetworkResponse-E<gt>B<_new> ($uri)

=over

=item * $uri (string) 

=back

=head2 $response-E<gt>B<_set_uri> ($uri)

=over

=item * $uri (string) 

=back



=cut


=head1 PROPERTIES

=over

=item 'message' (Glib::Object::_Unregistered::SoupMessage : default undef : readable / writable / construct-only / private)

The SoupMessage that backs the response.

=item 'suggested-filename' (string : default undef : readable / private)

The suggested filename for the response.

=item 'uri' (string : default undef : readable / writable / private)

The URI to which the response will be made.

=back



=cut


=head1 SEE ALSO

L<Gtk2::WebKit>, L<Glib::Object>


=cut


=head1 COPYRIGHT

Copyright (C) 2008, Florian Ragwitz


=cut

