=head1 NAME

Gtk2::WebKit::SecurityOrigin

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::WebKit::SecurityOrigin



=cut


=head1 METHODS

=head2 list = $security_origin-E<gt>B<get_all_web_databases> 

=head2 string = $security_origin-E<gt>B<get_host> 

=head2 integer = $security_origin-E<gt>B<get_port> 

=head2 string = $security_origin-E<gt>B<get_protocol> 

=head2 64 bit unsigned = $security_origin-E<gt>B<get_web_database_quota> 

=head2 $security_origin-E<gt>B<set_web_database_quota> ($quota)

=over

=item * $quota (64 bit unsigned) 

=back

=head2 64 bit unsigned = $security_origin-E<gt>B<get_web_database_usage> 



=cut


=head1 PROPERTIES

=over

=item 'host' (string : default undef : readable / private)

The host of the security origin

=item 'port' (Glib::UInt : default 0 : readable / private)

The port of the security origin

=item 'protocol' (string : default undef : readable / private)

The protocol of the security origin

=item 'web-database-quota' (Glib::UInt64 : default 0 : readable / writable / private)

The web database quota of the security origin in bytes

=item 'web-database-usage' (Glib::UInt64 : default 0 : readable / private)

The cumulative size of all web databases in the security origin

=back



=cut


=head1 SEE ALSO

L<Gtk2::WebKit>, L<Glib::Object>


=cut


=head1 COPYRIGHT

Copyright (C) 2008, Florian Ragwitz


=cut

