=head1 NAME

Gtk2::WebKit::WebDataSource

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::WebKit::WebDataSource



=cut


=head1 METHODS

=head2 webdatasource = Gtk2::WebKit::WebDataSource-E<gt>B<new> 

=head2 webdatasource = Gtk2::WebKit::WebDataSource-E<gt>B<new_with_request> ($request)

=over

=item * $request (Gtk2::WebKit::NetworkRequest) 

=back

=head2 scalar = $data_source-E<gt>B<get_data> 

=head2 string = $data_source-E<gt>B<get_encoding> 

=head2 networkrequest = $data_source-E<gt>B<get_initial_request> 

=head2 boolean = $data_source-E<gt>B<is_loading> 

=head2 webresource = $data_source-E<gt>B<get_main_resource> 

=head2 networkrequest = $data_source-E<gt>B<get_request> 

=head2 list = $data_source-E<gt>B<get_subresources> 

=head2 string = $data_source-E<gt>B<get_unreachable_uri> 

=head2 webframe = $data_source-E<gt>B<get_web_frame> 



=cut


=head1 SEE ALSO

L<Gtk2::WebKit>, L<Glib::Object>


=cut


=head1 COPYRIGHT

Copyright (C) 2008, Florian Ragwitz


=cut

