=head1 NAME

Gtk2::WebKit::WebSettings

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::WebKit::WebSettings



=cut


=head1 METHODS

=head2 websettings = Gtk2::WebKit::WebSettings-E<gt>B<new> 

=head2 websettings = $web_settings-E<gt>B<copy> 



=cut


=head1 PROPERTIES

=over

=item 'auto-load-images' (boolean : default true : readable / writable / construct / private)

Load images automatically.

=item 'auto-resize-window' (boolean : default false : readable / writable / construct / private)

Automatically resize the toplevel window when a page requests it

=item 'auto-shrink-images' (boolean : default true : readable / writable / construct / private)

Automatically shrink standalone images to fit.

=item 'cursive-font-family' (string : default "serif" : readable / writable / construct / private)

The default Cursive font family used to display text.

=item 'default-encoding' (string : default "iso-8859-1" : readable / writable / construct / private)

The default encoding used to display text.

=item 'default-font-family' (string : default "sans-serif" : readable / writable / construct / private)

The default font family used to display text.

=item 'default-font-size' (integer : default 12 : readable / writable / construct / private)

The default font size used to display text.

=item 'default-monospace-font-size' (integer : default 10 : readable / writable / construct / private)

The default font size used to display monospace text.

=item 'editing-behavior' (WebKitEditingBehavior : default "unix" : readable / writable / construct / private)

The behaviour mode to use in editing mode

=item 'enable-accelerated-compositing' (boolean : default false : readable / writable / construct / private)

Whether accelerated compositing should be enabled

=item 'enable-caret-browsing' (boolean : default false : readable / writable / construct / private)

Whether to enable accessibility enhanced keyboard navigation

=item 'enable-css-shaders' (boolean : default false : readable / writable / construct / private)

Whether to enable css shaders

=item 'enable-default-context-menu' (boolean : default true : readable / writable / construct / private)

Enables the handling of right-clicks for the creation of the default context menu

=item 'enable-developer-extras' (boolean : default false : readable / writable / construct / private)

Enables special extensions that help developers

=item 'enable-display-of-insecure-content' (boolean : default true : readable / writable / construct / private)

Whether non-HTTPS resources can display on HTTPS pages.

=item 'enable-dns-prefetching' (boolean : default true : readable / writable / construct / private)

Whether WebKit prefetches domain names

=item 'enable-dom-paste' (boolean : default false : readable / writable / construct / private)

Whether to enable DOM paste

=item 'enable-file-access-from-file-uris' (boolean : default false : readable / writable / construct / private)

Controls file access for file:// URIs.

=item 'enable-frame-flattening' (boolean : default false : readable / writable / construct / private)

Whether to enable Frame Flattening

=item 'enable-fullscreen' (boolean : default false : readable / writable / construct / private)

Whether the Mozilla style API should be enabled.

=item 'enable-html5-database' (boolean : default true : readable / writable / construct / private)

Whether to enable HTML5 database support

=item 'enable-html5-local-storage' (boolean : default true : readable / writable / construct / private)

Whether to enable HTML5 Local Storage support

=item 'enable-hyperlink-auditing' (boolean : default false : readable / writable / construct / private)

Whether <a ping> should be able to send pings

=item 'enable-java-applet' (boolean : default true : readable / writable / construct / private)

Whether Java Applet support through <applet> should be enabled

=item 'enable-media-stream' (boolean : default false : readable / writable / construct / private)

Whether Media Stream should be enabled

=item 'enable-offline-web-application-cache' (boolean : default true : readable / writable / construct / private)

Whether to enable offline web application cache

=item 'enable-page-cache' (boolean : default false : readable / writable / construct / private)

Whether the page cache should be used

=item 'enable-plugins' (boolean : default true : readable / writable / construct / private)

Enable embedded plugin objects.

=item 'enable-private-browsing' (boolean : default false : readable / writable / construct / private)

Enables private browsing mode

=item 'enable-running-of-insecure-content' (boolean : default true : readable / writable / construct / private)

Whether non-HTTPS resources can run on HTTPS pages.

=item 'enable-scripts' (boolean : default true : readable / writable / construct / private)

Enable embedded scripting languages.

=item 'enable-site-specific-quirks' (boolean : default false : readable / writable / construct / private)

Enables the site-specific compatibility workarounds

=item 'enable-smooth-scrolling' (boolean : default false : readable / writable / construct / private)

Whether to enable smooth scrolling

=item 'enable-spatial-navigation' (boolean : default false : readable / writable / construct / private)

Whether to enable Spatial Navigation

=item 'enable-spell-checking' (boolean : default false : readable / writable / construct / private)

Enables spell checking while typing

=item 'enable-universal-access-from-file-uris' (boolean : default false : readable / writable / construct / private)

Whether to allow universal access from file URIs

=item 'enable-webaudio' (boolean : default false : readable / writable / construct / private)

Whether WebAudio content should be handled

=item 'enable-webgl' (boolean : default false : readable / writable / construct / private)

Whether WebGL content should be rendered

=item 'enable-xss-auditor' (boolean : default true : readable / writable / construct / private)

Whether to enable the XSS auditor

=item 'enforce-96-dpi' (boolean : default false : readable / writable / construct / private)

Enforce a resolution of 96 DPI

=item 'fantasy-font-family' (string : default "serif" : readable / writable / construct / private)

The default Fantasy font family used to display text.

=item 'html5-local-storage-database-path' (string : default "/home/Yaakov/.local/share/webkit/databases" : readable / writable / construct / private)

The path to where HTML5 Local Storage databases are stored.

=item 'javascript-can-access-clipboard' (boolean : default false : readable / writable / construct / private)

Whether JavaScript can access Clipboard

=item 'javascript-can-open-windows-automatically' (boolean : default false : readable / writable / construct / private)

Whether JavaScript can open windows automatically

=item 'media-playback-allows-inline' (boolean : default true : readable / writable / construct / private)

Whether media playback allows inline

=item 'media-playback-requires-user-gesture' (boolean : default false : readable / writable / construct / private)

Whether media playback requires user gesture

=item 'minimum-font-size' (integer : default 5 : readable / writable / construct / private)

The minimum font size used to display text.

=item 'minimum-logical-font-size' (integer : default 5 : readable / writable / construct / private)

The minimum logical font size used to display text.

=item 'monospace-font-family' (string : default "monospace" : readable / writable / construct / private)

The default font family used to display monospace text.

=item 'print-backgrounds' (boolean : default true : readable / writable / construct / private)

Whether background images should be printed.

=item 'resizable-text-areas' (boolean : default true : readable / writable / construct / private)

Whether text areas are resizable.

=item 'respect-image-orientation' (boolean : default false : readable / writable / construct / private)

Whether WebKit should respect image orientation.

=item 'sans-serif-font-family' (string : default "sans-serif" : readable / writable / construct / private)

The default Sans Serif font family used to display text.

=item 'serif-font-family' (string : default "serif" : readable / writable / construct / private)

The default Serif font family used to display text.

=item 'spell-checking-languages' (string : default undef : readable / writable / construct / private)

Comma separated list of languages to use for spell checking

=item 'tab-key-cycles-through-elements' (boolean : default true : readable / writable / construct / private)

Whether the tab key cycles through elements on the page.

=item 'user-agent' (string : default "" : readable / writable / construct / private)

The User-Agent string used by WebKitGtk

=item 'user-stylesheet-uri' (string : default undef : readable / writable / construct / private)

The URI of a stylesheet that is applied to every page.

=item 'zoom-step' (float : default 0.1 : readable / writable / construct / private)

The value by which the zoom level is changed when zooming in or out.

=back



=cut


=head1 ENUMS AND FLAGS

=head2 enum WebKitEditingBehavior

=over

=item * 'mac' / 'WEBKIT_EDITING_BEHAVIOR_MAC'

=item * 'windows' / 'WEBKIT_EDITING_BEHAVIOR_WINDOWS'

=item * 'unix' / 'WEBKIT_EDITING_BEHAVIOR_UNIX'

=back




=cut


=head1 SEE ALSO

L<Gtk2::WebKit>, L<Glib::Object>


=cut


=head1 COPYRIGHT

Copyright (C) 2008, Florian Ragwitz


=cut

