/* This file is automatically generated. Any changes made here will be lost. */

/* This header defines simple perlapi-ish macros for creating SV wrappers
 * and extracting the GPerl value from SV wrappers.  These macros are used
 * by the autogenerated typemaps, and are defined here so that you can use
 * the same logic anywhere in your code (e.g., if you handle the argument
 * stack by hand instead of using the typemap). */

#ifdef GST_TYPE_PROPERTY_PROBE
  /* GInterface derivative GstPropertyProbe */
# define SvGstPropertyProbe(sv)	((GstPropertyProbe*)gperl_get_object_check (sv, GST_TYPE_PROPERTY_PROBE))
# define newSVGstPropertyProbe(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef GstPropertyProbe GstPropertyProbe_ornull;
# define SvGstPropertyProbe_ornull(sv)	(gperl_sv_is_defined (sv) ? SvGstPropertyProbe(sv) : NULL)
# define newSVGstPropertyProbe_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
#endif /* GST_TYPE_PROPERTY_PROBE */

#ifdef GST_TYPE_X_OVERLAY
  /* GInterface derivative GstXOverlay */
# define SvGstXOverlay(sv)	((GstXOverlay*)gperl_get_object_check (sv, GST_TYPE_X_OVERLAY))
# define newSVGstXOverlay(val)	(gperl_new_object (G_OBJECT (val), FALSE))
  typedef GstXOverlay GstXOverlay_ornull;
# define SvGstXOverlay_ornull(sv)	(gperl_sv_is_defined (sv) ? SvGstXOverlay(sv) : NULL)
# define newSVGstXOverlay_ornull(val)	(((val) == NULL) ? &PL_sv_undef : gperl_new_object (G_OBJECT (val), FALSE))
#endif /* GST_TYPE_X_OVERLAY */
