#define GST_INTERFACES_MAJOR_VERSION (0)
#define GST_INTERFACES_MINOR_VERSION (10)
#define GST_INTERFACES_MICRO_VERSION (36)
#define GST_INTERFACES_CHECK_VERSION(major,minor,micro) \
	(GST_INTERFACES_MAJOR_VERSION > (major) || \
	 (GST_INTERFACES_MAJOR_VERSION == (major) && GST_INTERFACES_MINOR_VERSION > (minor)) || \
	 (GST_INTERFACES_MAJOR_VERSION == (major) && GST_INTERFACES_MINOR_VERSION == (minor) && GST_INTERFACES_MICRO_VERSION >= (micro)))
