=head1 NAME

GStreamer::Event::NewSegment

=cut


=head1 METHODS

=head2 GstEvent = GStreamer::Event::NewSegment-E<gt>B<new> ($update, $rate, $format, $start_value, $stop_value, $stream_time)

=over

=item * $update (boolean) 

=item * $rate (double) 

=item * $format (GStreamer::Format) 

=item * $start_value (64 bit integer) 

=item * $stop_value (64 bit integer) 

=item * $stream_time (64 bit integer) 

=back

=head2 scalar = $event-E<gt>B<format> 

=head2 scalar = $event-E<gt>B<rate> 

=head2 scalar = $event-E<gt>B<start_value> 

=head2 scalar = $event-E<gt>B<stop_value> 

=head2 scalar = $event-E<gt>B<stream_time> 

=head2 scalar = $event-E<gt>B<update> 



=cut


=head1 ENUMS AND FLAGS

=head2 enum GStreamer::Format

=over

=item * 'undefined' / 'GST_FORMAT_UNDEFINED'

=item * 'default' / 'GST_FORMAT_DEFAULT'

=item * 'bytes' / 'GST_FORMAT_BYTES'

=item * 'time' / 'GST_FORMAT_TIME'

=item * 'buffers' / 'GST_FORMAT_BUFFERS'

=item * 'percent' / 'GST_FORMAT_PERCENT'

=back




=cut


=head1 SEE ALSO

L<GStreamer>


=cut


=head1 COPYRIGHT

Copyright (C) 2005-2014 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<GStreamer> for a full notice.



=cut

