=head1 NAME

GStreamer::Event::Tag

=cut


=head1 METHODS

=head2 GstEvent = GStreamer::Event::Tag-E<gt>B<new> ($taglist)

=over

=item * $taglist (GStreamer::TagList) 

=back

=head2 taglist = $event-E<gt>B<tag> 



=cut


=head1 SEE ALSO

L<GStreamer>


=cut


=head1 COPYRIGHT

Copyright (C) 2005-2014 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<GStreamer> for a full notice.



=cut

