=head1 NAME

GStreamer::Message::SegmentStart

=cut


=head1 METHODS

=head2 GstMessage = GStreamer::Message::SegmentStart-E<gt>B<new> ($src, $format, $position)

=over

=item * $src (GStreamer::Object) 

=item * $format (GStreamer::Format) 

=item * $position (64 bit integer) 

=back

=head2 scalar = $message-E<gt>B<format> 

=head2 scalar = $message-E<gt>B<position> 



=cut


=head1 ENUMS AND FLAGS

=head2 enum GStreamer::Format

=over

=item * 'undefined' / 'GST_FORMAT_UNDEFINED'

=item * 'default' / 'GST_FORMAT_DEFAULT'

=item * 'bytes' / 'GST_FORMAT_BYTES'

=item * 'time' / 'GST_FORMAT_TIME'

=item * 'buffers' / 'GST_FORMAT_BUFFERS'

=item * 'percent' / 'GST_FORMAT_PERCENT'

=back




=cut


=head1 SEE ALSO

L<GStreamer>


=cut


=head1 COPYRIGHT

Copyright (C) 2005-2014 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<GStreamer> for a full notice.



=cut

