=head1 NAME

GStreamer::Caps::Simple

=cut


=head1 METHODS

=head2 caps = GStreamer::Caps::Simple-E<gt>B<new> ($media_type, $field, $type, $value, ...)

=over

=item * $media_type (string) 

=item * $field (string) 

=item * $type (string) 

=item * $value (scalar) 

=item * ... (list) 

=back



=cut


=head1 SEE ALSO

L<GStreamer>


=cut


=head1 COPYRIGHT

Copyright (C) 2005-2014 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<GStreamer> for a full notice.



=cut

