=head1 NAME

Gtk2::SourceView2::LanguageManager

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::SourceView2::LanguageManager



=cut


=head1 METHODS

=head2 languagemanager = Gtk2::SourceView2::LanguageManager-E<gt>B<new> 

=head2 languagemanager = Gtk2::SourceView2::LanguageManager-E<gt>B<get_default> 

=head2 language or undef = $lm-E<gt>B<guess_language> ($filename, $content_type=undef)

=over

=item * $filename (string or undef) 

=item * $content_type (string or undef) 

=back

=head2 language or undef = $lm-E<gt>B<get_language> ($id)

=over

=item * $id (string) 

=back

=head2 list = $lm-E<gt>B<get_language_ids> 

=head2 list = $lm-E<gt>B<get_search_path> 

=head2 $lm-E<gt>B<set_search_path> (...)

=over

=item * ... (list) 

=back


Sets the list of directories where the lm looks for language files. If no dirs
are given (empty list) then the search path is cleared, if C<undef> is passed
then the search path is reset to default.

B<Note>: At the moment this function can be called only before the language
files are loaded for the first time. In practice to set a custom search path for
a Gtk2::SourceLanguageManager, you have to call this function right after
creating it.




=cut


=head1 PROPERTIES

=over

=item 'language-ids' (Glib::Strv : default undef : readable)

List of the ids of the available languages

=item 'search-path' (Glib::Strv : default undef : readable / writable)

List of directories where the language specification files (.lang) are located

=back



=cut


=head1 SEE ALSO

L<Gtk2::SourceView2>, L<Glib::Object>


=cut


=head1 COPYRIGHT

Copyright (C) 2009 by Emmanuel Rodriguez


=cut

