=head1 NAME

Gtk2::SourceView2::Mark

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::TextMark
       +----Gtk2::SourceView2::Mark



=cut


=head1 METHODS

=head2 mark = Gtk2::SourceView2::Mark-E<gt>B<new> ($name, $category)

=over

=item * $name (string or undef) 

=item * $category (string) 

=back

=head2 string = $mark-E<gt>B<get_category> 

=head2 mark or undef = $mark-E<gt>B<next> ($category)

=over

=item * $category (string or undef) 

=back

=head2 mark or undef = $mark-E<gt>B<prev> ($category)

=over

=item * $category (string or undef) 

=back



=cut


=head1 PROPERTIES

=over

=item 'category' (string : default undef : readable / writable / construct-only)

The mark category

=back



=cut


=head1 SEE ALSO

L<Gtk2::SourceView2>, L<Glib::Object>, L<Gtk2::TextMark>


=cut


=head1 COPYRIGHT

Copyright (C) 2009 by Emmanuel Rodriguez


=cut

